BigJobCpu: 16
BigJobMem: 32000
BigTime: 300
MediumTime: 120
SmallJobCpu: 1
SmallJobMem: 4000
SmallTime: 5
flyeModel: --nano-hq
input: complete_metadata.csv
log: 25_11_22_out/hybracter.log
long: true
medakaModel: r941_min_sup_g507
min_length: 1500
min_quality: 9
output: 25_11_22_out
polca: false
threads: 16
