site_name: hybracter
site_url: "https://github.com/gbouras13/hybracter"
site_author: George Bouras
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - shell
        - python
nav:
    - ABOUT:
      - Overview: index.md
      - Why Use hybracter?: reasons.md
      - Citation: citation.md
    - RUNNING:
      - Install: install.md
      - Commands and Input: input.md
      - Usage: run.md
      - Advanced Configuration: configuration.md
      - Snakemake Profiles: profiles.md
    - OUTPUT:
      - Output: output.md
    - BENCHMARKING:
      - Benchmarking: benchmarking.md
      - Ryan Wick and Lousie Judd's Dorado v0.5.0 Data: dorado_ryan_louise_0_5_0.md